services:
  postgres:
    image: postgres:15-alpine
    container_name: p2p-postgres
    environment:
      POSTGRES_DB: p2p_transfer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - p2p-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: p2p-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/p2p_transfer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - p2p-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: p2p-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - p2p-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  p2p-network:
    driver: bridge 